name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run iOS tests
      run: xcodebuild test -scheme SugarRecordTests -destination platform="iOS Simulator,name=iPhone 11 Pro"
